const list = [
    {
      id: 1,
      title: "AAshirvad Atta 5kg",
      author: "by ITC",
      price: 89,
      img: "https://www.bigbasket.com/media/uploads/p/l/126906_8-aashirvaad-atta-whole-wheat.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Paneer 200g",
      author: "by Amul",
      price: 90,
      img: "https://www.bigbasket.com/media/uploads/p/l/279588_7-amul-malai-paneer.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Paneer 200g",
      author: "by Mother Dairy",
      price: 85,
      img: "https://www.bigbasket.com/media/uploads/bpi/bangalore/l/40189284_3-mother-dairy-malai-paneer-rich-in-protein-calcium-made-from-cows-milk-creamy-for-snacks-gravy-dishes.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Fresh Carrot (orange) 500g",
      author: "by BigBasket ",
      price: 20,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000072_16-fresho-carrot-orange.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Onion 1kg",
      author: "by BigBasket ",
      price: 25,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000150_19-fresho-onion.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Tomato (hybrid) 500g",
      author: "by BigBasket",
      price: 10,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000201_15-fresho-tomato-hybrid.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Cauliflower 1pc",
      author: "by BigBasket",
      price: 25,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000074_19-fresho-cauliflower.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Capsicum (500g)",
      author: "by Amazon",
      price: 40,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000069_20-fresho-capsicum-green.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Cucumber (1kg) ",
      author: "by Amazon",
      price: 40,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000102_17-fresho-cucumber.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Broccoli (1pc)",
      author: "by MilkBasket",
      price: 26,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000063_20-fresho-broccoli.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Beatroot (1kg)",
      author: "by Amazon",
      price: 35,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000045_18-fresho-beetroot.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Bottle Gourd(500g)",
      author: "by Big Basket",
      price: 29,
      img: "https://www.bigbasket.com/media/uploads/p/l/20000745_5-fresho-bottle-gourd.jpg",
      amount: 1,
    },
    {
      id: 13,
      title: "Radish (white)(500g)",
      author: "by Big Basket",
      price: 18,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000166_16-fresho-radish-white.jpg",
      amount: 1,
    },
    {
      id: 14,
      title: "Colored Capsicum (500g)",
      author: "by Big Basket",
      price: 36,
      img: "https://www.bigbasket.com/media/uploads/p/l/40287310_1-fresho-coloured-capsicum-mix.jpg",
      amount: 1,
    },
    {
      id: 15,
      title: "Ginger (100g)",
      author: "by Amazon",
      price: 27,
      img: "https://www.bigbasket.com/media/uploads/p/l/50000509_5-fresho-ginger-organically-grown.jpg",
      amount: 1,
    },
    {
      id: 16,
      title: "Value Pack (Palak+Ladies Fingers+Capsicum(500g Each) +Cucumber+Bottle Gourd(1kg Each)Combo 5 Items",
      author: "by Big Basket",
      price: 204,
      img: "https://www.bigbasket.com/media/uploads/p/l/1209673_1-fresho-palakladies-fingercapsicum-green500g-eachcucumberbottle-gourd1kg-each.jpg",
      amount: 1,
    },
    {
      id: 17,
      title: "Brinjal(1kg)",
      author: "by MilkBasket",
      price: 67,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000053_18-fresho-brinjal-bottle-shape.jpg",
      amount: 1,
    },

    {
      id: 18,
      title: "Value Pack (Potato Onion Tomato 1 kg Each)",
      author: "by Amazon",
      price: 66,
      img: "https://www.bigbasket.com/media/uploads/p/l/1200045_1-fresho-potato-onion-tomato-1-kg-each.jpg",
      amount: 1,
    },{
      id: 19,
      title: "Banana(1kg)",
      author: "by amazon",
      price: 80,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000031_21-fresho-banana-yelakki.jpg",
      amount: 1,
    },{
      id: 20,
      title: "Pomegranate(1kg)",
      author: "by MilkBasket",
      price: 140,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000269_32-fresho-pomegranate.jpg",
      amount: 1,
    },{
      id: 21,
      title: "Watermelon(1kg)",
      author: "by Big Basket",
      price: 60,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000207_24-fresho-watermelon-small.jpg",
      amount: 1,
    },{
      id: 22,
      title: "Apple(1kg)",
      author: "by Big Basket",
      price: 120,
      img: "https://www.bigbasket.com/media/uploads/p/l/40033819_29-fresho-apple-shimla.jpg",
      amount: 1,
    },{
      id: 23,
      title: "Alphonso Mango(1kg)",
      author: "by Amazon",
      price: 580,
      img: "https://www.bigbasket.com/media/uploads/p/l/30001006_8-fresho-alphonso-mango-ratnagiri.jpg",
      amount: 1,
    },{
      id: 24,
      title: "Orange(1kg)",
      author: "by Big Basket",
      price: 75,
      img: "https://www.bigbasket.com/media/uploads/p/l/20000909_18-fresho-orange-imported.jpg",
      amount: 1,
    },{
      id: 25,
      title: "Avocado(500g)",
      author: "by Big Basket",
      price: 158,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000013_24-fresho-avocado.jpg",
      amount: 1,
    },{
      id: 26,
      title: "Dragon Fruit (1pc)",
      author: "by Big Basket",
      price: 101,
      img: "https://www.bigbasket.com/media/uploads/p/l/40008982_15-fresho-dragon-fruit.jpg",
      amount: 1,
    },{
      id: 27,
      title: "Muskmelon(1kg)",
      author: "by Amazon",
      price: 65,
      img: "https://www.bigbasket.com/media/uploads/p/l/40073761_7-fresho-muskmelon-striped.jpg",
      amount: 1,
    },{
      id: 28,
      title: "BB Royal Toor Dal/Togari Bele (1kg)",
      author: "by Big basket",
      price: 150,
      img: "https://www.bigbasket.com/media/uploads/p/l/40042841_7-bb-royal-toor-dalarhar-dal-desi.jpg",
      amount: 1,
    },{
      id: 29,
      title: "BB Popular Urad Dal (1kg)",
      author: "by Big basket",
      price: 150,
      img: "https://www.bigbasket.com/media/uploads/p/l/30010377_11-bb-popular-urad-dal-split.jpg",
      amount: 1,
    },{
      id: 30,
      title: "Toor Dal(1kg)",
      author: "by Tata Sampan",
      price: 145,
      img: "https://www.bigbasket.com/media/uploads/p/l/40000291_9-tata-sampann-unpolished-toor-dalarhar-dal.jpg",
      amount: 1,
    },{
      id: 31,
      title: "Moong Dal(1kg)",
      author: "by Tata Sampan",
      price: 140,
      img: "https://www.bigbasket.com/media/uploads/p/l/30002287_7-tata-sampann-unpolished-moong-dal.jpg",
      amount: 1,
    },{
      id: 32,
      title: "BB royal Chana Dal(1kg)",
      author: "by Big Basket",
      price: 186,
      img: "https://www.bigbasket.com/media/uploads/p/l/40042838_11-bb-royal-channa-dal.jpg",
      amount: 1,
    },{
      id: 33,
      title: "BB royal Masoor Dal(200g)",
      author: "by Big Basket",
      price: 30,
      img: "https://www.bigbasket.com/media/uploads/p/l/40058665_8-bb-popular-masoor-dal.jpg",
      amount: 1,
    },{
      id: 34,
      title: "Ragi Whole/Millet(1kg)",
      author: "by Big Basket",
      price: 62,
      img: "https://www.bigbasket.com/media/uploads/p/l/40203909_2-bb-royal-organic-ragi-wholefinger-millet.jpg",
      amount: 1,
    },{
      id: 35,
      title: "Fortune sunflower refined oil (3L)",
      author: "by MilkBasket",
      price: 378,
      img: "https://www.bigbasket.com/media/uploads/p/l/1204455_2-fortune-sunflower-refined-oil-sun-lite.jpg",
      amount: 1,
    },{
      id: 36,
      title: "Safola gold refined cooking oil (1L)",
      author: "by Big Basket",
      price: 170,
      img: "https://www.bigbasket.com/media/uploads/p/l/147491_9-saffola-gold-refined-cooking-oil-blended-rice-bran-sunflower-oil-helps-keeps-heart-healthy.jpg",
      amount: 1,
    },{
      id: 37,
      title: "BB Desi white Ghee 1L",
      author: "by Big Basket",
      price: 600,
      img: "https://www.bigbasket.com/media/uploads/p/l/40215102_6-bb-popular-desi-ghee.jpg",
      amount: 1,
    },
    {
      id: 38,
      title: " Figaro extra virgin olive oil 1L",
      author: "by Big Basket",
      price: 980,
      img: "https://www.bigbasket.com/media/uploads/p/l/40011505_6-figaro-extra-virgin-olive-oil.jpg",
      amount: 1,
    },
    {
      id: 39,
      title: "Del Monte extra virgin olive oil 250ml",
      author: "by Big Basket",
      price: 391,
      img: "https://www.bigbasket.com/media/uploads/p/l/40124641_6-del-monte-extra-virgin-olive-oil.jpg",
      amount: 1,
    },

    {
      id: 40,
      title: "Amul Butter",
      author: "by Big Basket",
      price: 53,
      img: "https://www.bigbasket.com/media/uploads/p/l/104860_8-amul-butter-pasteurised.jpg",
      amount: 1,
    },
    {
      id: 41,
      title: "BB royal rice 10Kg",
      author: "by Big Basket",
      price: 550,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000404_18-bb-royal-rice-raw-sona-masoori-12-17-months-old.jpg",
      amount: 1,
    },
    {
      id: 42,
      title: "BB Cashew 500g",
      author: "by Big Basket",
      price: 400,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000551_10-bb-popular-cashewkaju-whole.jpg",
      amount: 1,
    },
    
    {
      id: 43,
      title: "BB Royal Almonds 1kg",
      author: "by Big Basket",
      price: 1007,
      img: "https://www.bigbasket.com/media/uploads/p/l/40088564_8-bb-royal-almondbadam-californian-giri.jpg",
      amount: 1,
    },

    {
      id: 44,
      title: "BB popular Walnuts 200g",
      author: "by Big Basket",
      price: 280,
      img: "https://www.bigbasket.com/media/uploads/p/l/10000537_12-bb-popular-walnutakhrot-kernels-chile.jpg",
      amount: 1,
    },

    {
      id: 45,
      title: "BB Raisins 1000g",
      author: "by Big Basket",
      price: 203,
      img: "https://www.bigbasket.com/media/uploads/p/l/40021404_10-bb-popular-raisinskishmish-indian.jpg",
      amount: 1,
    },

    {
      id: 46,
      title: "Tata Iodised Salt 1kg",
      author: "by Tata",
      price: 25,
      img: "https://www.bigbasket.com/media/uploads/p/l/241600_7-tata-salt-iodized.jpg",
      amount: 1,
    },
    {
      id: 47,
      title: "Madhur Sugar- fine Grain 1kg",
      author: "by Big Basket",
      price: 50,
      img: "https://www.bigbasket.com/media/uploads/p/l/40253563_1-madhur-sugar-pure-hygienic-fine-grain-natural-sulphur-free.jpg",
      amount: 1,
    },
    {
      id: 48,
      title: "BB Royal organic-Brown sugar 1kg",
      author: "by Big Basket",
      price: 79,
      img: "https://www.bigbasket.com/media/uploads/p/l/40075302_14-bb-royal-organic-brown-sugar.jpg",
      amount: 1,
    },
    {
      id: 49,
      title: "Amul Taza Homogenised Toned Milk 500L",
      author: "by Big Basket",
      price: 37,
      img: "https://www.bigbasket.com/media/uploads/p/l/40041431_1-amul-taaza-fresh-toned-milk.jpg",
      amount: 1,
    },
    {
      id: 50,
      title: "Amul Gold Milk 1L",
      author: "by Big Basket",
      price: 79,
      img: "https://www.bigbasket.com/media/uploads/p/l/104707_8-amul-homogenised-standardised-milk.jpg",
      amount: 1,
    },
    {
      id: 51,
      title: "Amul Masti Buttermilk 200ml",
      author: "by Big Basket",
      price: 13,
      img: "https://www.bigbasket.com/media/uploads/p/l/161899_9-amul-masti-buttermilk-spice.jpg",
      amount: 1,
    },

    {
      id: 52,
      title: "Paper Boat Buttermilk 250ml",
      author: "by Big Basket",
      price: 30,
      img: "https://www.bigbasket.com/media/uploads/p/l/40193427_6-paper-boat-coriander-buttermilk.jpg",
      amount: 1,
    },
    {
      id: 52,
      title: "Hershey's Syrup Chocolate",
      author: "by Amazon",
      price: 170,
      img: "https://m.media-amazon.com/images/I/71pouMfvcfS._SX679_.jpg",
      amount: 1,
    },
    {
      id: 53,
      title: "Nutella Hazelnut Spread with Cocoa 350g",
      author: "by Amazon",
      price: 323,
      img: "https://www.bigbasket.com/media/uploads/p/l/40094923_9-nutella-hazelnut-spread-with-cocoa.jpg",
      amount: 1,
    },
    
];

export default list;